version:                                    '3.5'
services:
  db:
    image: mysql:8.0.32
    command:                                --default-authentication-plugin=mysql_native_password
    restart:                                always
    volumes:
      - ./sql/thepack.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../thePackMySQL:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:                  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:                       odinms 
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - internal-net
    container_name:                         db
  app:
    build:
        context:                              ./
        dockerfile:                         app.Dockerfile
    restart:                                always
    depends_on:
      - "db"     
    environment:
      WAIT_HOSTS:                           db:3306 
    ports:
      - '7575:7575'
      - '7576:7576'
      - '7577:7577'
      - '7578:7578'
      - '8484:8484'
    expose:
      - '7575'
      - '7576'
      - '7577'
      - '7578'
      - '8484'
    networks:
      - internal-net
    container_name:                         app
networks:
  internal-net:
    name:                                   internal-net
