version: '3.5'
services:
  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql/thepack.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../thePackMySQL:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: odinms
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - internal-net
    container_name: db
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    depends_on:
      - "db"
      - "elasticsearch"
      - "kibana"
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - '7575:7575'
      - '7576:7576'
      - '7577:7577'
      - '7578:7578'
      - '8484:8484'
    expose:
      - '7575'
      - '7576'
      - '7577'
      - '7578'
      - '8484'
    networks:
      - internal-net
    container_name: app
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  elasticsearch:
    image: elasticsearch:7.14.2
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=es-docker
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - LOGSPOUT=ignore
      - discovery.type=single-node
    container_name: elasticsearch
    networks:
      - internal-net
  kibana:
    image: kibana:7.14.2
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGSPOUT: ignore
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    container_name: kibana
    networks:
      - internal-net
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
    networks:
      - internal-net
    container_name: filebeat
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.15
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch
    container_name: logstash
    networks:
      - internal-net
networks:
  internal-net:
    name: internal-net
